/*
each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89...

By considering the terms in the Fibonacci sequence whose values do not exceed four milion, find the sum of the even-valued terms.
*/

let soma = 0;

function Fibonacci(n) {
    if (n <= 1) return n;
    result = Fibonacci(n - 1) + Fibonacci(n - 2);
    return result
}

for (i = 0; soma <= 4000000; i++) {
    if (Fibonacci(i) % 2 == 0) soma += Fibonacci(i);
}

console.log(soma)